import json

# Define the mappings
mappings_to_highest_level = {
    "poor": "Class and education",
    "middle class": "Class and education",
    "upper class": "Class and education",
    "heirs": "Class and education",
    "investors and stakeholders": "Class and education",
    "underprivileged": "Class and education",
    "qualified": "Class and education",
    "working active population": "Professional status and social protection",
    "employees": "Professional status and social protection",
    "precarious employees": "Professional status and social protection",
    "people working in the public sector": "Professional status and social protection",
    "employers": "Professional status and social protection",
    "self-employed/freelancers": "Professional status and social protection",
    "unemployed": "Professional status and social protection",
    "seniors": "Professional status and social protection",
    "housewife and househusband": "Professional status and social protection",
    "people without public social protection": "Professional status and social protection",
    "insured persons": "Professional status and social protection",
    "enterprises": "Enterprises",
    "small- and middle-size enterprises": "Enterprises",
    "large enterprises": "Enterprises",
    "specific sector": "Enterprises",
    "men": "Demographic groups and family status",
    "women": "Demographic groups and family status",
    "minors": "Demographic groups and family status",
    "youth": "Demographic groups and family status",
    "middle-aged": "Demographic groups and family status",
    "parents and families": "Demographic groups and family status",
    "older age group": "Demographic groups and family status",
    "elderly": "Demographic groups and family status",
    "couples": "Demographic groups and family status",
    "singles": "Demographic groups and family status",
    "binationals": "Minorities and identities",
    "disabled": "Minorities and identities",
    "immigrants": "Minorities and identities",
    "ethnic Germans": "Minorities and identities",
    "language or ethnic minorities": "Minorities and identities",
    "visible minorities": "Minorities and identities",
    "religious groups": "Minorities and identities",
    "christians": "Minorities and identities",
    "religious minorities": "Minorities and identities",
    "jews": "Minorities and identities",
    "muslims": "Minorities and identities",
    "LGBTQI*": "Minorities and identities",
    "home owner": "Real estate ownership",
    "land owner": "Real estate ownership",
    "landlords": "Real estate ownership",
    "tenants": "Real estate ownership",
    "homeless": "Real estate ownership",
    "farmers and fishermen": "Professional category",
    "health and care professionals": "Professional category",
    "doctors": "Professional category",
    "social professions": "Professional category",
    "teachers and educators": "Professional category",
    "scientists": "Professional category",
    "engineers": "Professional category",
    "journalists": "Professional category",
    "legal professionals": "Professional category",
    "security forces": "Professional category",
    "soldiers": "Professional category",
    "politicians and high-ranking officials": "Professional category",
    "prostitutes": "Professional category",
    "road carriers": "Professional category",
    "lobbyists": "Professional category",
    "leaders": "Professional category",
    "athletes": "Professional category",
    "authors and artists": "Professional category",
    "East Germans": "Territorial group",
    "West Germans": "Territorial group",
    "inhabitants of cities": "Territorial group",
    "inhabitants of rural or underserved areas": "Territorial group",
    "inhabitants of underprivileged areas": "Territorial group",
    "inhabitants of overseas": "Territorial group",
    "inhabitants of other areas": "Territorial group",
    "expatriates": "Territorial group",
    "consumers": "Behavioral groups",
    "air travellers": "Behavioral groups",
    "car drivers": "Behavioral groups",
    "cyclists": "Behavioral groups",
    "pedestrians": "Behavioral groups",
    "public transport passengers": "Behavioral groups",
    "commuters": "Behavioral groups",
    "drug addicts": "Behavioral groups",
    "smokers": "Behavioral groups",
    "whistle-blower and witnesses": "Behavioral groups",
    "offenders or criminals": "Behavioral groups",
    "tax evaders and white collar criminals": "Behavioral groups",
    "terrorists": "Behavioral groups",
    "extremists": "Behavioral groups",
    "volunteers": "Behavioral groups",
    "hunters": "Behavioral groups",
    "gun owners": "Behavioral groups",
    "patients": "Others",
    "tax payers": "Others",
    "victims of German history": "Others",
    "victims of crimes": "Others",
    "others": "Others",
    "Others": "Others"
}


mappings_to_intermediary_level = {
    "poor": "poor",
    "middle class": "middle class",
    "upper class": "upper class",
    "heirs": "heirs",
    "investors and stakeholders": "investors and stakeholders",
    "underprivileged": "underprivileged",
    "qualified": "qualified",
    "working active population": "working active population",
    "employees": "working active population",
    "precarious employees": "working active population",
    "people working in the public sector": "working active population",
    "employers": "working active population",
    "self-employed/freelancers": "working active population",
    "unemployed": "working active population",
    "seniors": "seniors",
    "housewife and househusband": "housewife and househusband",
    "people without public social protection": "people without public social protection",
    "insured persons": "insured persons",
    "enterprises": "enterprises",
    "small- and middle-size enterprises": "enterprises",
    "large enterprises": "enterprises",
    "specific sector": "enterprises",
    "men": "men",
    "women": "women",
    "minors": "minors",
    "youth": "youth",
    "middle-aged": "middle-aged",
    "parents and families": "parents and families",
    "older age group": "older age group",
    "elderly": "elderly",
    "couples": "couples",
    "singles": "singles",
    "binationals": "binationals",
    "disabled": "disabled",
    "immigrants": "immigrants",
    "ethnic Germans": "ethnic Germans",
    "language or ethnic minorities": "language or ethnic minorities",
    "visible minorities": "visible minorities",
    "religious groups": "religious groups",
    "christians": "religious groups",
    "religious minorities": "religious groups",
    "jews": "religious groups",
    "muslims": "religious groups",
    "LGBTQI*": "LGBTQI*",
    "home owner": "home owner",
    "land owner": "land owner",
    "landlords": "landlords",
    "tenants": "tenants",
    "homeless": "homeless",
    "farmers and fishermen": "farmers and fishermen",
    "health and care professionals": "health and care professionals",
    "doctors": "health and care professionals",
    "social professions": "social professions",
    "teachers and educators": "teachers and educators",
    "scientists": "scientists",
    "engineers": "engineers",
    "journalists": "journalists",
    "legal professionals": "legal professionals",
    "security forces": "security forces",
    "soldiers": "soldiers",
    "politicians and high-ranking officials": "politicians and high-ranking officials",
    "prostitutes": "prostitutes",
    "road carriers": "road carriers",
    "lobbyists": "lobbyists",
    "leaders": "leaders",
    "athletes": "athletes",
    "authors and artists": "authors and artists",
    "East Germans": "East Germans",
    "West Germans": "West Germans",
    "inhabitants of cities": "inhabitants of cities",
    "inhabitants of rural or underserved areas": "inhabitants of rural or underserved areas",
    "inhabitants of underprivileged areas": "inhabitants of underprivileged areas",
    "inhabitants of overseas": "inhabitants of overseas",
    "inhabitants of other areas": "inhabitants of other areas",
    "expatriates": "expatriates",
    "consumers": "consumers",
    "air travellers": "consumers",
    "car drivers": "consumers",
    "cyclists": "consumers",
    "pedestrians": "consumers",
    "public transport passengers": "consumers",
    "commuters": "commuters",
    "drug addicts": "drug addicts",
    "smokers": "smokers",
    "whistle-blower and witnesses": "whistle-blower and witnesses",
    "offenders or criminals": "offenders or criminals",
    "tax evaders and white collar criminals": "offenders or criminals",
    "terrorists": "terrorists",
    "extremists": "extremists",
    "volunteers": "volunteers",
    "hunters": "hunters",
    "gun owners": "gun owners",
    "patients": "patients",
    "tax payers": "tax payers",
    "victims of German history": "victims of German history",
    "victims of crimes": "victims of crimes",
    "others": "others",
    "Others": "Others"
}


def transform_jsonl(input_file, output_file, mappings):
    with open(input_file, 'r', encoding='utf-8') as infile, open(output_file, 'w', encoding='utf-8') as outfile:
        for row_idx, line in enumerate(infile):
            data = json.loads(line)
            groups = data["groups"]
            upper_categories = [mappings.get(group, group) for group in groups]
            transformed_data = {
                "id": data["id"],
                "rowIdx": data["rowIdx"],
                "groups": upper_categories,
                "text": data["text"]
            }
            outfile.write(json.dumps(transformed_data, ensure_ascii=False) + '\n')

# Define files
input_file = 'groups_per_sentence_G_lowest_level.jsonl'  
output_file = 'groups_per_sentence_G_highest_level.jsonl'

# Transform file
transform_jsonl(input_file, output_file, mappings_to_highest_level)

# Define files
input_file = 'groups_per_sentence_G_lowest_level.jsonl'  
output_file = 'groups_per_sentence_G_intermediary_level.jsonl'

# Transform file
transform_jsonl(input_file, output_file, mappings_to_intermediary_level)

